/********************************************************************
* libTAUn_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error libTAUn_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelibTAUn_Dict();
extern void G__cpp_setup_inheritancelibTAUn_Dict();
extern void G__cpp_setup_typetablelibTAUn_Dict();
extern void G__cpp_setup_memvarlibTAUn_Dict();
extern void G__cpp_setup_globallibTAUn_Dict();
extern void G__cpp_setup_memfunclibTAUn_Dict();
extern void G__cpp_setup_funclibTAUn_Dict();
extern void G__set_cpp_environmentlibTAUn_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "taun_vars.h"
#include "TauData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__libTAUn_DictLN_TClass;
extern G__linked_taginfo G__libTAUn_DictLN_TBuffer;
extern G__linked_taginfo G__libTAUn_DictLN_TMemberInspector;
extern G__linked_taginfo G__libTAUn_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__libTAUn_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libTAUn_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__libTAUn_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libTAUn_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__libTAUn_DictLN_TTree;
extern G__linked_taginfo G__libTAUn_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__libTAUn_DictLN_TauData;

/* STUB derived class for protected member access */
